export const SEED_RECIPES = [
  {
    title: "High-Protein Greek Yogurt Bowl",
    description: "A protein-rich breakfast that's easy on a sensitive stomach",
    ingredients: [
      { name: "Greek yogurt (nonfat)", amount: "1", unit: "cup" },
      { name: "Mixed berries", amount: "1/2", unit: "cup" },
      { name: "Chia seeds", amount: "1", unit: "tbsp" },
      { name: "Honey", amount: "1", unit: "tsp" },
    ],
    instructions: [
      "Add yogurt to a bowl",
      "Top with mixed berries",
      "Sprinkle chia seeds",
      "Drizzle with honey",
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 220,
    protein: 20,
    carbs: 28,
    fat: 4,
    tags: ["breakfast", "high-protein", "quick", "no-cook"],
    glp1FriendlyNotes:
      "Small portions, protein-rich. Easy to eat when appetite is reduced.",
  },
  {
    title: "Grilled Chicken Salad",
    description:
      "Light and filling lunch with lean protein and crisp vegetables",
    ingredients: [
      { name: "Chicken breast", amount: "4", unit: "oz" },
      { name: "Mixed greens", amount: "2", unit: "cups" },
      { name: "Cherry tomatoes", amount: "1/2", unit: "cup" },
      { name: "Cucumber", amount: "1/2", unit: "medium" },
      { name: "Lemon juice", amount: "1", unit: "tbsp" },
      { name: "Olive oil", amount: "1", unit: "tsp" },
    ],
    instructions: [
      "Season chicken breast with salt, pepper, and garlic powder",
      "Grill chicken over medium-high heat 6-7 minutes per side until cooked through",
      "Let chicken rest 5 minutes, then slice",
      "Combine greens, tomatoes, and cucumber in a bowl",
      "Top with sliced chicken",
      "Drizzle with lemon juice and olive oil",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    calories: 280,
    protein: 38,
    carbs: 8,
    fat: 9,
    tags: ["lunch", "high-protein", "low-carb", "gluten-free"],
    glp1FriendlyNotes:
      "High protein keeps you satisfied with a small portion. Light dressing avoids heavy fats that can cause nausea.",
  },
  {
    title: "Baked Salmon with Roasted Vegetables",
    description:
      "Omega-3 rich salmon with colorful vegetables for a nutritious dinner",
    ingredients: [
      { name: "Salmon fillet", amount: "5", unit: "oz" },
      { name: "Broccoli florets", amount: "1", unit: "cup" },
      { name: "Bell pepper", amount: "1/2", unit: "medium" },
      { name: "Zucchini", amount: "1/2", unit: "medium" },
      { name: "Olive oil", amount: "1", unit: "tsp" },
      { name: "Lemon", amount: "1/2", unit: "medium" },
      { name: "Dill", amount: "1", unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 400°F",
      "Toss vegetables with olive oil, salt, and pepper on a baking sheet",
      "Place salmon on the same sheet, season with dill, salt, and pepper",
      "Roast for 20-22 minutes until salmon flakes easily",
      "Squeeze fresh lemon over everything before serving",
    ],
    prepTime: 10,
    cookTime: 22,
    servings: 1,
    calories: 340,
    protein: 36,
    carbs: 14,
    fat: 15,
    tags: ["dinner", "high-protein", "omega-3", "gluten-free", "meal-prep"],
    glp1FriendlyNotes:
      "Omega-3s support overall health. Baking is gentler than frying, easier to digest.",
  },
  {
    title: "Egg White Veggie Muffins",
    description: "Portable meal-prep breakfast bites packed with protein",
    ingredients: [
      { name: "Egg whites", amount: "6", unit: "large" },
      { name: "Baby spinach", amount: "1/2", unit: "cup" },
      { name: "Cherry tomatoes", amount: "1/4", unit: "cup" },
      { name: "Red onion", amount: "2", unit: "tbsp" },
      { name: "Feta cheese (reduced fat)", amount: "2", unit: "tbsp" },
      { name: "Black pepper", amount: "1/4", unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 350°F and spray a muffin tin with cooking spray",
      "Chop spinach, tomatoes, and red onion",
      "Divide vegetables evenly among 6 muffin cups",
      "Whisk egg whites with pepper and pour over vegetables",
      "Sprinkle feta cheese on top",
      "Bake 18-20 minutes until set and lightly golden",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    calories: 45,
    protein: 7,
    carbs: 2,
    fat: 1,
    tags: ["breakfast", "low-carb", "meal-prep", "low-fat"],
    glp1FriendlyNotes:
      "Perfect portion-controlled bites. Make a batch Sunday for the whole week. Very low calorie per muffin.",
  },
  {
    title: "Turkey Lettuce Wraps",
    description:
      "Crisp lettuce cups filled with seasoned ground turkey — no bun needed",
    ingredients: [
      { name: "Ground turkey (93% lean)", amount: "4", unit: "oz" },
      { name: "Butter lettuce leaves", amount: "3", unit: "large" },
      { name: "Water chestnuts", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "1", unit: "clove" },
      { name: "Low-sodium soy sauce", amount: "1", unit: "tbsp" },
      { name: "Fresh ginger", amount: "1/4", unit: "tsp" },
      { name: "Green onion", amount: "1", unit: "tbsp" },
    ],
    instructions: [
      "Cook ground turkey in a skillet over medium heat, breaking it up",
      "Add minced garlic and ginger, cook 1 minute",
      "Stir in soy sauce and water chestnuts",
      "Cook until turkey is fully cooked and liquid is absorbed",
      "Spoon mixture into lettuce cups",
      "Garnish with sliced green onion",
    ],
    prepTime: 5,
    cookTime: 12,
    servings: 1,
    calories: 240,
    protein: 30,
    carbs: 9,
    fat: 8,
    tags: ["lunch", "high-protein", "low-carb", "quick"],
    glp1FriendlyNotes:
      "Lettuce wraps are easier on digestion than bread. The small portions are ideal when appetite is suppressed.",
  },
  {
    title: "Lemon Herb Chicken Breast",
    description:
      "Simple baked chicken with bright lemon and herb flavors, never dry",
    ingredients: [
      { name: "Boneless chicken breast", amount: "5", unit: "oz" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Garlic powder", amount: "1/2", unit: "tsp" },
      { name: "Dried oregano", amount: "1/2", unit: "tsp" },
      { name: "Dried thyme", amount: "1/4", unit: "tsp" },
      { name: "Olive oil", amount: "1", unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 375°F",
      "Mix lemon juice, olive oil, and spices to form a marinade",
      "Coat chicken breast with marinade",
      "Bake in covered dish for 25-28 minutes until internal temp reaches 165°F",
      "Rest 5 minutes before slicing",
    ],
    prepTime: 5,
    cookTime: 28,
    servings: 1,
    calories: 210,
    protein: 39,
    carbs: 2,
    fat: 5,
    tags: ["dinner", "high-protein", "low-fat", "low-carb", "gluten-free"],
    glp1FriendlyNotes:
      "Very lean, high protein. Cover while baking to retain moisture — important when nausea makes dry foods unpleasant.",
  },
  {
    title: "High-Protein Smoothie",
    description:
      "Quick protein-packed snack or small meal for low-appetite days",
    ingredients: [
      { name: "Vanilla protein powder", amount: "1", unit: "scoop" },
      { name: "Unsweetened almond milk", amount: "1", unit: "cup" },
      { name: "Frozen banana", amount: "1/2", unit: "medium" },
      { name: "Spinach", amount: "1/2", unit: "cup" },
      { name: "Almond butter", amount: "1", unit: "tbsp" },
    ],
    instructions: [
      "Add all ingredients to a blender",
      "Blend on high until smooth, about 60 seconds",
      "Serve immediately or refrigerate up to 24 hours",
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 310,
    protein: 30,
    carbs: 24,
    fat: 9,
    tags: ["snack", "high-protein", "quick", "no-cook"],
    glp1FriendlyNotes:
      "Ideal when solid food is unappealing. Sip slowly. Spinach adds nutrients without altering taste.",
  },
  {
    title: "Cottage Cheese Veggie Bowl",
    description:
      "Savory high-protein snack bowl — no cooking required",
    ingredients: [
      { name: "Low-fat cottage cheese", amount: "1/2", unit: "cup" },
      { name: "Cherry tomatoes", amount: "1/4", unit: "cup" },
      { name: "Cucumber", amount: "1/4", unit: "cup" },
      { name: "Everything bagel seasoning", amount: "1/2", unit: "tsp" },
      { name: "Fresh chives", amount: "1", unit: "tbsp" },
    ],
    instructions: [
      "Spoon cottage cheese into a bowl",
      "Halve cherry tomatoes and dice cucumber",
      "Top cottage cheese with vegetables",
      "Sprinkle with everything bagel seasoning and chives",
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 110,
    protein: 14,
    carbs: 8,
    fat: 2,
    tags: ["snack", "high-protein", "quick", "no-cook", "low-fat"],
    glp1FriendlyNotes:
      "Cottage cheese is gentle on the stomach and very filling per calorie. Great for days when appetite is low.",
  },
  {
    title: "Zucchini Noodle Stir-Fry",
    description:
      "Low-carb noodle alternative with shrimp and vibrant stir-fry sauce",
    ingredients: [
      { name: "Zucchini (spiralized)", amount: "2", unit: "medium" },
      { name: "Shrimp (peeled, deveined)", amount: "4", unit: "oz" },
      { name: "Bell pepper", amount: "1/2", unit: "medium" },
      { name: "Snap peas", amount: "1/2", unit: "cup" },
      { name: "Low-sodium soy sauce", amount: "1", unit: "tbsp" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Fresh ginger", amount: "1/2", unit: "tsp" },
    ],
    instructions: [
      "Spiralize zucchini and set aside on paper towels to absorb moisture",
      "Heat sesame oil in a large skillet or wok over high heat",
      "Add garlic and ginger, stir-fry 30 seconds",
      "Add shrimp and cook 2-3 minutes until pink",
      "Add bell pepper and snap peas, stir-fry 2 minutes",
      "Add zucchini noodles and soy sauce, toss 1-2 minutes until just tender",
      "Serve immediately",
    ],
    prepTime: 10,
    cookTime: 10,
    servings: 1,
    calories: 230,
    protein: 28,
    carbs: 16,
    fat: 6,
    tags: ["dinner", "low-carb", "high-protein", "quick", "gluten-free"],
    glp1FriendlyNotes:
      "Zucchini noodles are much lighter than pasta — important when fullness comes quickly. High volume, low calorie.",
  },
] as const;
